Systemy Baz Danych/config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :bands
  resources :concerts
  resources :tickets
  resources :people
  resources :home, only: [:index]
  resources :search, only: [:index]

  resources :festivals do
    member do
      post 'increase_prices'
    end
  end

  root to: 'home#index'

end

Systemy Baz Danych/app/models/band.rb
class Band < ActiveRecord::Base
  include PgSearch

  pg_search_scope :search, against: [:name, :genre, :formed_on, :country, :about]

  validates_presence_of :name, :genre, :formed_on, :country

  validates :formed_on, numericality: { greater_than_or_equal_to: 1900, less_than_or_equal_to: 2017 }

  has_many :concerts
end

Systemy Baz Danych/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json

  def index
    if params[:query].present?
      @bands = Band.search(params[:query]).order(params[:order]).order(:id)
    else
      @bands = Band.order(params[:order]).order(:id)
    end
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :genre, :formed_on, :country, :about, :id)
    end
end

Systemy Baz Danych/app/helpers/bands_helper.rb
module BandsHelper
end

Systemy Baz Danych/app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :formed_on %><br>
    <%= f.select :formed_on, Array(1900..2017).reverse.collect { |a| [a.to_s, a] }, { include_blank: true } %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.select :country, ISO3166::Country.translations("PL").each.select { |k,v| v }.map { |a| [a[1], a[1]] }.sort, { include_blank: true } %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Systemy Baz Danych/app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'List bands', bands_path %>

Systemy Baz Danych/app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bands</h1>

<%= form_tag bands_path, method: :get do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag 'Search', class: "button" %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Id', bands_path(order: 'id') %></th>
      <th><%= link_to 'Name', bands_path(order: 'name') %></th>
      <th><%= link_to 'Genre', bands_path(order: 'genre') %></th>
      <th><%= link_to 'Formed on', bands_path(order: 'formed_on') %></th>
      <th><%= link_to 'Country', bands_path(order: 'country') %></th>
      <th><%= link_to 'About', bands_path(order: 'about') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.id %></td>
        <td><%= band.name %></td>
        <td><%= band.genre %></td>
        <td><%= band.formed_on %></td>
        <td><%= band.country %></td>
        <td><%= band.about %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Delete', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New band', new_band_path %>
<%= link_to 'Home Page', root_url %>

Systemy Baz Danych/app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form' %>

<%= link_to 'List bands', bands_path %>

Systemy Baz Danych/app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band.name %>
</p>

<p>
  <strong>Id:</strong>
  <%= @band.id %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @band.genre %>
</p>

<p>
  <strong>Formed on:</strong>
  <%= @band.formed_on %>
</p>

<p>
  <strong>Country:</strong>
  <%= @band.country %>
</p>

<p>
  <strong>About:</strong>
  <%= @band.about %>
</p>

<% if @band.concerts.count > 0 %>
  <h2>Concerts</h2>
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @band.concerts.each do |concert| %>
        <tr>
          <td><%= concert.id %></td>
          <td><%= concert.name %></td>
          <td><%= concert.date %></td>
          <td><%= link_to 'Show', concert %></td>
          <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
          <td><%= link_to 'Delete', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'List bands', bands_path %> |
<%= link_to 'Home Page', root_path %>