Systemy Baz Danych/config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :bands
  resources :concerts
  resources :tickets
  resources :people
  resources :home, only: [:index]
  resources :search, only: [:index]

  resources :festivals do
    member do
      post 'increase_prices'
    end
  end

  root to: 'home#index'

end

Systemy Baz Danych/app/models/concert.rb
class Concert < ActiveRecord::Base
  include PgSearch

  pg_search_scope :search, against: [:name, :date]

  validates_presence_of :name, :date, :location_id, :festival_id, :band_id

  # validates :name, format: { with: /\A[a-zA-Z]+\z/,
  #   message: "only allows letters" }

  # validates_format_of :date, :with => /\d{4}-\d{2}-\d{2}/, message: "^Date must be in the following format: yyyy-mm-dd"

  belongs_to :band
  belongs_to :location
  belongs_to :festival
end

Systemy Baz Danych/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:show, :edit, :update, :destroy]

  # GET /concerts
  # GET /concerts.json
  def index
    if params[:query].present?
      @concerts = Concert.search(params[:query]).order(params[:order]).order(:id)
    else
      @concerts = Concert.order(params[:order]).order(:id)
    end
  end

  # GET /concerts/1
  # GET /concerts/1.json
  def show
    @location = @concert.location
    @band = @concert.band
    @festival = @concert.festival
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit

  end

  # POST /concerts
  # POST /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Concert was successfully created.' }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1
  # PATCH/PUT /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to @concert, notice: 'Concert was successfully updated.' }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: 'Concert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_params
      params.require(:concert).permit(:name, :date, :id, :location_id, :band_id, :festival_id)
    end
end

Systemy Baz Danych/app/helpers/concerts_helper.rb
module ConcertsHelper
end

Systemy Baz Danych/app/views/concerts/_form.html.erb
<%= form_for(@concert) do |f| %>
  <% if @concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% @concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, { include_blank: true } %>
  </div>

  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.select :location_id, Location.all.collect { |f| [f.name, f.id] }, { include_blank: true } %>
  </div>

  <div class="field">
    <%= f.label :band_id %><br>
    <%= f.select :band_id, Band.all.collect { |f| [f.name, f.id] }, { include_blank: true } %>
  </div>

  <div class="field">
    <%= f.label :festival_id %><br>
    <%= f.select :festival_id, Festival.all.collect { |f| [f.name, f.id] }, { include_blank: true } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Systemy Baz Danych/app/views/concerts/edit.html.erb
<h1>Editing Concert</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert %> |
<%= link_to 'List concerts', concerts_path %>

Systemy Baz Danych/app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concerts</h1>

<%= form_tag concerts_path, method: :get do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag 'Search', class: "button" %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Id', concerts_path(order: 'id') %></th>
      <th><%= link_to 'Name', concerts_path(order: 'name') %></th>
      <th><%= link_to 'Date', concerts_path(order: 'date') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.id %></td>
        <td><%= concert.name %></td>
        <td><%= concert.date %></td>
        <td><%= link_to 'Show', concert %></td>
        <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
        <td><%= link_to 'Delete', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new concert', new_concert_path %>
<%= link_to 'Home Page', root_url %>

Systemy Baz Danych/app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= render 'form' %>

<%= link_to 'List concerts', concerts_path %>

Systemy Baz Danych/app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @concert.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @concert.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @concert.date %>
</p>


<%= link_to 'Edit', edit_concert_path(@concert) %> |
<%= link_to 'List concerts', concerts_path %> |
<%= link_to 'Home Page', root_path %>

<% if @band %>
  <h2>Band</h2>

  <p>
    <strong>Name:</strong>
    <%= @band.name %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= @band.genre %>
  </p>

  <p>
    <strong>Formed on:</strong>
    <%= @band.formed_on %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= @band.country %>
  </p>

  <p>
    <strong>About:</strong>
    <%= @band.about %>
  </p>

  <%= link_to 'Edit', edit_band_path(@band) %> |
  <%= link_to 'List bands', bands_path %>
<% end %>

<% if @location %>
  <h2>Location</h2>

  <p>
    <strong>Name:</strong>
    <%= @location.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @location.address %>
  </p>

  <p>
    <strong>Opened at:</strong>
    <%= @location.opened_at %>
  </p>

  <p>
    <strong>Closed at:</strong>
    <%= @location.closed_at %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= @location.capacity %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @location.phone_number %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= @location.website %>
  </p>

  <%= link_to 'Edit', edit_location_path(@location) %> |
  <%= link_to 'List locations', locations_path %>
<% end %>

<% if @festival %>

  <h2>Festival</h2>

  <p>
    <strong>Name:</strong>
    <%= @festival.name %>
  </p>

  <p>
    <strong>Edition:</strong>
    <%= @festival.edition %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= @festival.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= @festival.end_date %>
  </p>

  <%= link_to 'Edit', edit_festival_path(@festival) %> |
  <%= link_to 'List festivals', festivals_path %>
<% end %>