Systemy Baz Danych/config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :bands
  resources :concerts
  resources :tickets
  resources :people
  resources :home, only: [:index]
  resources :search, only: [:index]

  resources :festivals do
    member do
      post 'increase_prices'
    end
  end

  root to: 'home#index'

end

Systemy Baz Danych/app/models/location.rb
class Location < ActiveRecord::Base
  include PgSearch

  pg_search_scope :search, against: [:name, :address, :opened_at, :closed_at, :capacity, :phone_number, :website]

  validates_presence_of :name, :address, :opened_at, :closed_at, :capacity, :phone_number
  validates :capacity, numericality: { greater_than_or_equal_to: 0 }

  validate :check_opened_at
  validate :check_closed_at

  def check_opened_at
    errors.add(:opened_at, "- invalid format. Valid format example: 18:00") unless Tod::TimeOfDay.parsable?(opened_at)
  end

  def check_closed_at
    errors.add(:closed_at, "- invalid format. Valid format example: 18:00") unless Tod::TimeOfDay.parsable?(closed_at)
  end

  before_save :parse_opened_at, :parse_closed_at

  has_many :concerts

  protected

  def parse_opened_at
    Tod::TimeOfDay.parse(opened_at)
  end

  def parse_closed_at
    Tod::TimeOfDay.parse(closed_at)
  end
end

Systemy Baz Danych/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    if params[:query].present?
      @locations = Location.search(params[:query]).order(params[:order]).order(:id)
    else
      @locations = Location.order(params[:order]).order(:id)
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :address, :opened_at, :closed_at, :capacity, :phone_number, :website, :id)
    end
end

Systemy Baz Danych/app/helpers/locations_helper.rb
module LocationsHelper
end

Systemy Baz Danych/app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :opened_at %><br>
    <%= f.text_field :opened_at, placeholder: 'np. 18:00' %>
  </div>
  <div class="field">
    <%= f.label :closed_at %><br>
    <%= f.text_field :closed_at, placeholder: 'np. 24:00' %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.number_field :phone_number, placeholder: '601256503' %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Systemy Baz Danych/app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'List locations', locations_path %>

Systemy Baz Danych/app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<%= form_tag locations_path, method: :get do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag 'Search', class: "button" %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Id', locations_path(order: 'id') %></th>
      <th><%= link_to 'Name', locations_path(order: 'name') %></th>
      <th><%= link_to 'Address', locations_path(order: 'address') %></th>
      <th><%= link_to 'Opened at', locations_path(order: 'opened_at') %></th>
      <th><%= link_to 'Closed at', locations_path(order: 'closed_at') %></th>
      <th><%= link_to 'Capacity', locations_path(order: 'capacity') %></th>
      <th><%= link_to 'Phone number', locations_path(order: 'phone_number') %></th>
      <th><%= link_to 'Website', locations_path(order: 'website') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.id %></td>
        <td><%= location.name %></td>
        <td><%= location.address %></td>
        <td><%= location.opened_at %></td>
        <td><%= location.closed_at %></td>
        <td><%= location.capacity %></td>
        <td><%= location.phone_number %></td>
        <td><%= location.website %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new location', new_location_path %>
<%= link_to 'Home Page', root_url %>

Systemy Baz Danych/app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'List locations', locations_path %>

Systemy Baz Danych/app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @location.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Opened at:</strong>
  <%= @location.opened_at %>
</p>

<p>
  <strong>Closed at:</strong>
  <%= @location.closed_at %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @location.capacity %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @location.phone_number %>
</p>

<p>
  <strong>Website:</strong>
  <%= @location.website %>
</p>

<% if @location.concerts.count > 0 %>
  <h2>Concerts</h2>
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @location.concerts.each do |concert| %>
        <tr>
          <td><%= concert.id %></td>
          <td><%= concert.name %></td>
          <td><%= concert.date %></td>
          <td><%= link_to 'Show', concert %></td>
          <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
          <td><%= link_to 'Delete', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'List locations', locations_path %> |
<%= link_to 'Home Page', root_path %>