Systemy Baz Danych/config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :bands
  resources :concerts
  resources :tickets
  resources :people
  resources :home, only: [:index]
  resources :search, only: [:index]

  resources :festivals do
    member do
      post 'increase_prices'
    end
  end

  root to: 'home#index'

end

Systemy Baz Danych/app/models/festival.rb
class Festival < ActiveRecord::Base
  include PgSearch

  pg_search_scope :search, against: [:name, :edition, :start_date, :end_date]

  validates_presence_of :name, :edition, :start_date, :end_date

  validates :edition, numericality: { greater_than_or_equal_to: 0 }

  validate :validate_end_date_before_start_date

  has_many :concerts, dependent: :destroy
  has_many :tickets, dependent: :destroy


  def validate_end_date_before_start_date
    if end_date && start_date
      errors.add(:end_date, "must occur after start date") if end_date < start_date
    end
  end
end

Systemy Baz Danych/app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  before_action :set_festival, only: [:show, :edit, :update, :destroy]

  # GET /festivals
  # GET /festivals.json
  def index
    if params[:query].present?
      @festivals = Festival.search(params[:query]).order(params[:order]).order(:id)
    else
      @festivals = Festival.order(params[:order]).order(:id)
    end
  end

  # GET /festivals/1
  # GET /festivals/1.json
  def show
    @tickets = @festival.tickets
    @concerts = @festival.concerts
    sql_statement = "SELECT zlicz_sprzedane_bilety(" + params[:id] + ");"
    @tickets_sold = ActiveRecord::Base.connection.execute(sql_statement).values[0][0].to_i
  end

  def increase_prices
    s_percentage = 10;
    n_percentage = 20;
    sql_statement = "SELECT podwyzka_cen_biletow(" + s_percentage.to_s + "," + n_percentage.to_s + ");"
    ActiveRecord::Base.connection.execute('BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;')
    ActiveRecord::Base.connection.execute(sql_statement)
    ActiveRecord::Base.connection.execute('COMMIT;')

    redirect_to festival_path(params[:id])
  end

  # GET /festivals/new
  def new
    @festival = Festival.new
  end

  # GET /festivals/1/edit
  def edit
  end

  # POST /festivals
  # POST /festivals.json
  def create
    @festival = Festival.new(festival_params)

    respond_to do |format|
      if @festival.save
        format.html { redirect_to @festival, notice: 'Festival was successfully created.' }
        format.json { render :show, status: :created, location: @festival }
      else
        format.html { render :new }
        format.json { render json: @festival.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /festivals/1
  # PATCH/PUT /festivals/1.json
  def update
    respond_to do |format|
      if @festival.update(festival_params)
        format.html { redirect_to @festival, notice: 'Festival was successfully updated.' }
        format.json { render :show, status: :ok, location: @festival }
      else
        format.html { render :edit }
        format.json { render json: @festival.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /festivals/1
  # DELETE /festivals/1.json
  def destroy
    @festival.destroy
    respond_to do |format|
      format.html { redirect_to festivals_url, notice: 'Festival was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_festival
      @festival = Festival.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def festival_params
      params.require(:festival).permit(:name, :edition, :start_date, :end_date, :id)
    end
end

Systemy Baz Danych/app/helpers/festivals_helper.rb
module FestivalsHelper
end

Systemy Baz Danych/app/views/festivals/_form.html.erb
<%= form_for(@festival) do |f| %>
  <% if @festival.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@festival.errors.count, "error") %> prohibited this festival from being saved:</h2>

      <ul>
      <% @festival.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :edition %><br>
    <%= f.text_field :edition %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, { include_blank: true } %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date, { include_blank: true } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Systemy Baz Danych/app/views/festivals/edit.html.erb
<h1>Editing Festival</h1>

<%= render 'form' %>

<%= link_to 'Show', @festival %> |
<%= link_to 'List festivals', festivals_path %>

Systemy Baz Danych/app/views/festivals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Festivals</h1>

<%= form_tag festivals_path, method: :get do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag 'Search', class: "button" %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Id', festivals_path(order: 'id') %></th>
      <th><%= link_to 'Name', festivals_path(order: 'name') %></th>
      <th><%= link_to 'Edition', festivals_path(order: 'edition') %></th>
      <th><%= link_to 'Start date', festivals_path(order: 'start_date') %></th>
      <th><%= link_to 'End date', festivals_path(order: 'end_date') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @festivals.each do |festival| %>
      <tr>
        <td><%= festival.id %></td>
        <td><%= festival.name %></td>
        <td><%= festival.edition %></td>
        <td><%= festival.start_date %></td>
        <td><%= festival.end_date %></td>
        <td><%= link_to 'Show', festival %></td>
        <td><%= link_to 'Edit', edit_festival_path(festival) %></td>
        <td><%= link_to 'Delete', festival, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add new festival', new_festival_path %>
<%= link_to 'Home Page', root_url %>

Systemy Baz Danych/app/views/festivals/new.html.erb
<h1>New Festival</h1>

<%= render 'form' %>

<%= link_to 'List festivals', festivals_path %>

Systemy Baz Danych/app/views/festivals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @festival.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @festival.name %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @festival.edition %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @festival.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @festival.end_date %>
</p>

<%= link_to 'Edit', edit_festival_path(@festival) %> |
<%= link_to 'List festivals', festivals_path %> |
<%= link_to 'Home Page', root_path %>

<h2>Available tickets: <%= @tickets_sold %></h2>

<% if @tickets.count > 0 %>
  <%= form_tag increase_prices_festival_url(@festival) do %>
    <%= submit_tag "Increase discounted tickets' prices by 10% and normal ones by 20%", class: "button" %>
  <% end %>
<% end %>

<% if @tickets_sold > 0 %>
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Price</th>
        <th>Category</th>
        <th>Valid from</th>
        <th>Valid to</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.id %></td>
          <td><%= ticket.price %></td>
          <td><%= ticket.category %></td>
          <td><%= ticket.valid_from %></td>
          <td><%= ticket.valid_to %></td>
          <td><%= link_to 'Show', ticket %></td>
          <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
          <td><%= link_to 'Delete', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if @concerts.count > 0 %>
  <h2>Concerts</h2>

  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @concerts.each do |concert| %>
        <tr>
          <td><%= concert.id %></td>
          <td><%= concert.name %></td>
          <td><%= concert.date %></td>
          <td><%= link_to 'Show', concert %></td>
          <td><%= link_to 'Edit', edit_concert_path(concert) %></td>
          <td><%= link_to 'Delete', concert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>